#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")

apiVersion: v1
kind: Secret
metadata:
  name: elephantsql-service-broker
  namespace: elephantsql-service-broker
type: Opaque
data:
  spring_security_user_password: #@ base64.encode(data.values.spring_security_user_password)
  elephantsql_api_key: #@ base64.encode(data.values.elephantsql_api_key)