apiVersion: v1
kind: Service
metadata:
  labels:
    app: elephantsql-service-broker
  name: elephantsql-service-broker
  namespace: elephantsql-service-broker
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: elephantsql-service-broker
  type: ClusterIP