name: CI
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: mvn test
      env:
        ELEPHANTSQL_API_KEY: ${{ secrets.ELEPHANTSQL_API_KEY }}
      run: |
        set -e
        ./mvnw -V test
    - name: mvn deploy
      if: github.ref == 'refs/heads/master'
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: |
        set -e
        BOOT_VERSION=$(grep '<version>' pom.xml | head -n 1 | sed -e 's|<version>||g' -e 's|</version>||g' -e 's|<.*>||g' -e 's| ||g')
        cat > settings.xml <<EOF
        <settings>
          <servers>
            <server>
               <id>sonatype-snapshots</id>
               <username>${SONATYPE_USERNAME}</username>
               <password>${SONATYPE_PASSWORD}</password>
            </server>
          </servers>
        </settings>
        EOF
        ./mvnw -V deploy -s settings.xml -DskipTests=true -Dspring-boot.version=${BOOT_VERSION} -DserverId=sonatype-snapshots
    - name: pack build
      if: github.ref == 'refs/heads/master'
      env:
        PACK_VERSION: 0.11.0
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        set -e
        docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
        wget -q https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz
        tar xzf pack-*.tgz
        rm -f pack-*.tgz
        ./pack build making/elephantsql-service-broker \
          -p target/elephantsql-service-broker-*.jar  \
          --builder gcr.io/paketo-buildpacks/builder:base
        docker push making/elephantsql-service-broker